#!/bin/sh /etc/rc.common
# Projo server
# Copyright (C) 2007 OpenWrt.org
 
START=99
STOP=99

DAEMON="/srv/projo/server.py"
PID_FILE="/var/run/projo.pid"

start() {        
    start-stop-daemon -S -b -m -p $PID_FILE -x $DAEMON
}                 
 
stop() {          
    start-stop-daemon -K -p $PID_FILE
}
